Updated travis.yml
prasadtalasila/MailingListParser pull request #118
Opened 2018-01-14 12:40 UTC by AakankshaSanctis

Changes proposed in this pull request:
-Updated the travis.yml with the latest email id of project contributors

## Notify reviewers
@achyudhk

2018-01-14 15:47 UTC, prasadtalasila commented
@AakankshaSanctis please update the README.md and etc/deploy_docs.sh files as well. @achyudhk has already made some modifications to the READNE.md. Do update the code coverage badge and cross check for the required name changes.

2018-01-14 19:17 UTC, AakankshaSanctis commented
There is a link in the README.md for test_driver.py file (https://github.com/achyudhk/Mailing-List-Network-Analyzer/blob/development/lib/test_driver.py) which no longer  exists.@achyudhk can you look into it and put the appropriate file link.

2018-01-14 19:32 UTC, AakankshaSanctis commented
1.  README.md
   1.  etc/deploy_docs.sh
   1.   project outline
   1.  travis.yml

have been updated

2018-01-14 19:35 UTC, AakankshaSanctis commented
codecov and dependency badges have been added but integration needs to be done

2018-01-15 01:24 UTC, prasadtalasila requested changes

2018-01-15 01:24 UTC, prasadtalasila commented on README.md
>  [![Requirements Status](https://requires.io/github/DeveloperCAP/MLCAT/requirements.svg?branch=master)](https://requires.io/github/DeveloperCAP/MLCAT/requirements/?branch=master)
@AakankshaSanctis please remove the requires.io badge. We have a versioneye badge which is serving the same purpose.

2018-01-15 04:01 UTC, AakankshaSanctis commented
README.md updated with removal of requirements.io badge

2018-01-15 04:25 UTC, merged