Update Templates
prasadtalasila/MailingListParser pull request #133
Opened 2018-01-23 16:38 UTC by naveen-hr

## What? Why?
Fix #124  

Changes proposed in this pull request:
- CODE_OF CONDUCT.md added
- CONTRIBUTING.md added
- ISSUE_TEMPLATE.md added
- PULL_REQUEST_TEMPLATE.md added
- Above files added to .github/ 

## Checks
- [ ] Single commit and [No merge commits](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Make sure you have added required documentation
- [ ] If you have refactored a code, make sure that you have compared the outputs pre and post refactoring. Add both pre and post refaoring screenshots below if the output is visual

## Any images?

## Notify reviewers
@prasadtalasila

2018-01-23 17:49 UTC, prasadtalasila requested changes
@naveen-hr please make the requested changes.

2018-01-23 17:49 UTC, prasadtalasila commented on .github/CONTRIBUTING.md
> +Thank you for contributing to Slack Community Analysis Tool (SCAT)!
The tool name should be Mailing List Community Analysis Tool (MLCAT).

2018-01-23 17:49 UTC, prasadtalasila commented on .github/CONTRIBUTING.md
> +The [style guidelines](https://github.com/DeveloperCAP/SCAT/wiki/Coding-Guidelines) wiki page defines the source file coding standards used in this project.
Please update the URL.

2018-01-23 17:49 UTC, prasadtalasila commented on .github/CONTRIBUTING.md
> +* Ensure that your pull request follows the [style guidelines](https://github.com/DeveloperCAP/SCAT/wiki/Coding-Guidelines)
Please update the URL.

2018-01-23 17:49 UTC, prasadtalasila commented on .github/PULL_REQUEST_TEMPLATE.md
> + - [ ] Ensure that your pull request follows the [style guidelines](https://github.com/rohangoel96/Slack-Community-Analysis-Tool/wiki/Coding-Guidelines)
please update the URL.

2018-01-24 16:48 UTC, naveen-hr commented
The requested changes have been done.

2018-01-24 17:52 UTC, prasadtalasila approved these changes

2018-01-24 17:52 UTC, merged