Integration tests
prasadtalasila/MailingListParser pull request #153
Opened 2018-02-17 17:32 UTC by hrishikesh-dahiya

## Description
 - Integration tests for `curve_fitting.py`, `wh_table.py`, `ranking.py`
 - #152

## Motivation
 - Increase code coverage
 
 ## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checks
 - [ ] Squash your commits down to one, or a few, discreet changesets before submitting a pull request
 - [ ] Read the [contributing guide](https://github.com/DeveloperCAP/MLCAT/blob/development/.github/CONTRIBUTING.md)
 - [ ] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [ ] If possible, include an example in the description, that could help all readers (including project members) to get a better picture of the change
 - [ ] Avoid other runtime dependencies unless absolutely necessary 
 - [ ] Rebase your commit history so that each commit is meaningful and states the intention behind the change 
 - [ ] Ensure that your pull request follows the [style guidelines](https://github.com/DeveloperCAP/MLCAT/wiki/Coding-Guidelines)
 - [ ] At least one commit should mention `Fixes #152` _if relevant_

## Notify reviewers
@prasadtalasila

2018-02-17 17:39 UTC, hrishikesh-dahiya commented
@prasadtalasila Is there a way to fix this codeclimate issue? https://codeclimate.com/github/DeveloperCAP/MLCAT/pull/153

2018-02-17 18:10 UTC, prasadtalasila requested changes
@hrishikesh-dahiya please see the requested changes.

2018-02-17 18:10 UTC, prasadtalasila commented on lib/analysis/author/wh_table.py
> +        lone_author_threads = get_lone_author_threads(nodelist_filename=nodelist_filename, edgelist_filename=edgelist_filename)
This kind of explicit mapping of arguments to parameters is done only when you have more than three parameters. Here, it might be better to use positional parameter association (see [ref](https://www.pythoncentral.io/fun-with-python-function-parameters/)). Given that the argument and parameter names match, it does not make sense to have named parameter assignment.

2018-02-17 18:10 UTC, prasadtalasila commented on test/integration_test/lib/analysis/author/test_ranking.py
> +opensuse-kernel@opensuse.org,5,1
The usual convention for indentation is to offset the following lines to align with the string that you are concatenating. In this particular case, the vertical alignment can happen at Email word.

2018-02-17 18:10 UTC, prasadtalasila commented on test/integration_test/lib/analysis/author/test_wh_table.py
> +    req_file_data1 = """Height(h),Number of authors(i)
`req_file_data1`, `req_file_data2` can be put in two different files in test/integration_test/data/ directory. You can port the `save_to_disk()` and `load_from_disk()` functions of [util.py](https://github.com/prasadtalasila/IRCLogParser/blob/master/lib/util.py#L240-L260) module from IRCLogParser project. They will come in very handy during testing.

2018-02-18 11:03 UTC, hrishikesh-dahiya commented on lib/analysis/author/wh_table.py
> +        lone_author_threads = get_lone_author_threads(nodelist_filename=nodelist_filename, edgelist_filename=edgelist_filename)
`read.py` has many dependencies. I would create another PR for rectifying this problem.

2018-02-18 11:26 UTC, prasadtalasila approved these changes

2018-02-18 11:27 UTC, merged