[Test] Integration tests for analysis/author/
prasadtalasila/MailingListParser pull request #160
Opened 2018-03-12 15:16 UTC by hrishikesh-dahiya

## Description
Integration Tests for the following:
- [ ] community.py
- [ ] edge_list.py
- [ ] time_statistics.py

Fixes #152 

## Motivation
 - To increase the code coverage

 ## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checks
 - [ ] Squash your commits down to one, or a few, discreet changesets before submitting a pull request
 - [ ] Read the [contributing guide](https://github.com/DeveloperCAP/MLCAT/blob/development/.github/CONTRIBUTING.md)
 - [ ] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [ ] If possible, include an example in the description, that could help all readers (including project members) to get a better picture of the change
 - [ ] Avoid other runtime dependencies unless absolutely necessary 
 - [ ] Rebase your commit history so that each commit is meaningful and states the intention behind the change 
 - [ ] Ensure that your pull request follows the [style guidelines](https://github.com/DeveloperCAP/MLCAT/wiki/Coding-Guidelines)
 - [ ] At least one commit should mention `Fixes #152` _if relevant_

## Notify reviewers
@prasadtalasila

2018-03-12 15:22 UTC, hrishikesh-dahiya commented
@prasadtalasila The tests run fine on my system but [Travis](https://travis-ci.org/DeveloperCAP/MLCAT/jobs/352385189) is showing some error in test_community.py. 
Any solution to it?

2018-03-15 11:48 UTC, prasadtalasila requested changes

2018-03-15 11:48 UTC, prasadtalasila commented on test/integration_test/data/author_graph.net
>  *vertices 15
all the test specific temporary files are stored in .tmp directory and are removed at the end of tests.

Please modify etc/pytest.sh to have the following lines
```bash
#!/bin/bash
mkdir .tmp
py.test -v --color=yes --cov=.
rm -rf .tmp
codecov
```

2018-03-15 11:48 UTC, prasadtalasila commented on test/integration_test/lib/analysis/author/test_community.py
> +    vertex_clustering(json_filename, nodelist_filename, edgelist_filename, foldername)
Modify `vertex_clustering()` so that:
* Between lines-264 and 265, `vertex_dendogram` gets saved to a text file and gets asserted during the test.

2018-03-15 11:48 UTC, prasadtalasila commented on test/integration_test/lib/analysis/author/test_community.py
> +
path all the invocations of igraph.plot()

2018-03-15 11:48 UTC, prasadtalasila commented on test/integration_test/lib/analysis/author/test_community.py
> +    assert 'Clustering with 15 elements and 4 clusters' in load_from_disk(foldername+'community_vertex_clustering.txt')
The travis.yml needs to be suitable modified to install the required dependencies. For the necessary commands, please see [install_deps.sh](https://github.com/DeveloperCAP/MLCAT/blob/master/etc/install_deps.sh).

2018-03-15 11:48 UTC, prasadtalasila commented on test/integration_test/lib/analysis/author/test_edge_list.py
> +
Please add sphinx docs for the underlying method, `generate_edge_list`.

2018-03-15 11:48 UTC, prasadtalasila commented on lib/analysis/author/edge_list.py
> +					   edgelist_filename, threads_json_filename, author_json_filename, ignore_lat=True):
generate_edge_list(author_nodes, author_edges, lat_nodes, lat_edges, ...)

2018-03-15 11:48 UTC, prasadtalasila commented on test/integration_test/lib/analysis/author/test_time_statistics.py
> +    assert conversation_refresh_times(headers_filename, graph_nodes, graph_edges, foldername) == None
Please test for return of "No Messages"

2018-03-15 11:48 UTC, prasadtalasila commented
The changes suggested in this PR are to be brought in as two separate PRs.

2018-03-15 11:48 UTC, closed without merging