integration test for lib/util/union_find.py
prasadtalasila/MailingListParser pull request #161
Opened 2018-03-13 14:34 UTC by tejalwakchoure

Fixes #143 
## Notify reviewers
@prasadtalasila

2018-03-15 10:13 UTC, prasadtalasila requested changes

2018-03-15 10:13 UTC, prasadtalasila commented on test/integration_test/lib/util/test_union_find.py
> +def test_union_find(self):
The class name should be `TestUnionFind` and have one test method for each method that is getting tested.

2018-03-17 17:18 UTC, prasadtalasila commented
@tejalwakchoure  Please add tests to make sure you have all the code lines covered by tests (near 100% code coverage).

2018-03-19 09:04 UTC, tejalwakchoure commented
@prasadtalasila Updated. The lines that are still not covered pertain to private functions so I am not sure how to test them.

2018-03-19 09:29 UTC, prasadtalasila commented
@tejalwakchoure The lines that are not covered by the test are: [39 to 41](https://codecov.io/gh/DeveloperCAP/MLCAT/pull/161/changes#L39). These lines belong to make_set() function; this function is not private. You can invoke make_set() such that the conditions on lines 34 and 36 get bypassed and you get a chance to execute lines 39 to 41.

2018-03-19 10:12 UTC, prasadtalasila commented
Looks good.

2018-03-19 10:12 UTC, prasadtalasila approved these changes

2018-03-19 10:13 UTC, merged