[Test] Integration test for community.py
prasadtalasila/MailingListParser pull request #171
Opened 2018-03-26 08:33 UTC by hrishikesh-dahiya

## Description
 - Integration test for community.py
 - Two methods of community.py moved to deprecated/
 - Fixes #152 

## Motivation
 - To increase code coverage
 
 ## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checks
 - [ ] Squash your commits down to one, or a few, discreet changesets before submitting a pull request
 - [ ] Read the [contributing guide](https://github.com/DeveloperCAP/MLCAT/blob/development/.github/CONTRIBUTING.md)
 - [ ] PR should be motivated, i.e. what does it fix, why, and if relevant how
 - [ ] If possible, include an example in the description, that could help all readers (including project members) to get a better picture of the change
 - [ ] Avoid other runtime dependencies unless absolutely necessary 
 - [ ] Rebase your commit history so that each commit is meaningful and states the intention behind the change 
 - [ ] Ensure that your pull request follows the [style guidelines](https://github.com/DeveloperCAP/MLCAT/wiki/Coding-Guidelines)
 - [ ] At least one commit should mention `Fixes #152` _if relevant_

## Notify reviewers
@prasadtalasila

2018-03-26 19:33 UTC, prasadtalasila commented
@hrishikesh-dahiya please resolve the merge conflict.

2018-03-27 09:15 UTC, hrishikesh-dahiya commented
@prasadtalasila there are no merge conflicts in this PR, though travis CI is erroring in installation of igraph dependency

2018-04-06 01:24 UTC, prasadtalasila requested changes

2018-04-06 01:24 UTC, prasadtalasila commented on etc/install_deps.sh
>  #!/bin/bash
given that this file is being tailored for travis deployment, it is better to name this as `travis_installs.sh` and keep the original `install_deps.sh` for local installations.

2018-04-06 01:24 UTC, prasadtalasila commented on etc/igraph.sh
> +wget http://switch.dl.sourceforge.net/sourceforge/igraph/igraph-0.5.4.tar.gz
We can probably invoke this script inside `travis_installs.sh` and `install_deps.sh`

2018-04-08 10:23 UTC, prasadtalasila commented
@hrishikesh-dahiya good work on this PR.

2018-04-08 10:24 UTC, prasadtalasila approved these changes

2018-04-08 10:24 UTC, merged